/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_fileselection (void);
GtkWidget* create_dialog2 (void);
GtkWidget* create_error_window (void);
GtkWidget* create_nonosefart_error (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_audio_error (void);
